services:
  postgres:
    image: postgres:17
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: happy_pet_shop

  redis:
    image: redis:8
    ports:
      - "6379:6379"
  kafka:
    image: apache/kafka:4.0.0
    ports:
      - "9092:9092"